### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by negativchik09** [negativchik09/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by CollaboratorNegativchik** [comment]
Шерлок Холмс, народився 6 січня 1854 року. "Консультуючий" детектив, розробник дедуктивного методу в криміналістиці. При розслідуванні справ опираюсь скоріше не на букву закону, а на власні життєві принципи. Невибагливий, байдужий до роскоші та комфорту, здатний працювати за будь-яких умов.
