### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by negativchik09** [negativchik09/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by CollaboratorNegativchik** [comment]
Адреса: Великобританія, Лондон, Бейкер-Стріт 221Б. Що? Цієї адреси не існує? А де тоді знаходиться музей, що мені присвячений. Так, мені присвячено музей, не заздріть.
