### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by negativchik09** [negativchik09/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by CollaboratorNegativchik** [comment]
Перша справа була розкрита ще у коледжі влітку 1875 року. Розповідь про ті події отримала назву "Глорія Скотт".
У 1881 році познайомився з доктором Ватсоном, що і описав більшу частину моїх справ.
Справа, з якої розпочинається цикл розповідей описана у творі "Етюд у багряних тонах". В той раз все почалось із дивного вбивства американця, біля тіла якого хтось кривенько вивів слово "Помста"...
Далі відбулась низка гучних справ, під час яких я розвивав власні навички як криміналіста, та відточував знання. Приведу як приклад найвідоміші із них:
- Знак чотирьох
- Скандал в Богемії
- Строката стрічка
- Беррилієва діадема
- Обряд дому Мейсгрейвів
Ледве не помер при розплутуванні справи, яка пізніше отримала назву "Остання справа Холмса". Взагалі, чому це Ватсон вирішив, що то була моя остання справа. Подумаєш, увесь Лондон думав, що я загинув, ну то й що з того.
Так, з'явилась необхідність втекти і ховатись 3 роки, хоча я вам скажу, що то булі не найгірші роки: я подорожував, відвідав Тибет, Персію, Мекку, побував із візитом у халіфа в Хартумі. Опісля провів декілька місяців на півдні Франції, вивчаючи властивості кам'яновугільних смол. За часи подорожей значно вдосконалились навички акторської гри та розширились межі відомого, що, безумовно, покращило мене як спеціаліста
Повернувшись до Лондона взявся за справу "Собака Баскервілей", яка досить довгий час вважалась містичною, а я в містику не вірю, тому і вирішив розвіяти завісу таємничості навколо тих подій.
Після того продовжував практику "консультуючого" детектива як і раніше.
